/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class frm_principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_principal
     */
    public frm_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_aceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_palabras = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_primeraletra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_repetira = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_repetire = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_repetiri = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_repetiro = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_repetiru = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_ultimaletra = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lbl_ultima = new javax.swing.JLabel();
        lbl_primerapalabra = new javax.swing.JLabel();
        lbl_ultima1 = new javax.swing.JLabel();
        lbl_ultimapalabra = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_central = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_par = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_impar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        copiar = new javax.swing.JMenuItem();
        pegar = new javax.swing.JMenuItem();
        cortar = new javax.swing.JMenuItem();
        mayuscula = new javax.swing.JMenuItem();
        minuscula = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Total de caracteres: ");

        lbl_cantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_cantidad.setForeground(new java.awt.Color(0, 0, 255));

        lbl_aceptar.setText("Procesar");
        lbl_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_aceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad de palabras: ");

        lbl_palabras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_palabras.setForeground(new java.awt.Color(0, 0, 255));

        jLabel3.setText("Primera letra del texto:");

        lbl_primeraletra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_primeraletra.setForeground(new java.awt.Color(0, 0, 255));

        jLabel4.setText("Veces que aparece A, a, á");

        lbl_repetira.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repetira.setForeground(new java.awt.Color(0, 0, 255));

        jLabel5.setText("Veces que aparece E, e, é");

        lbl_repetire.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repetire.setForeground(new java.awt.Color(0, 0, 255));

        jLabel6.setText("Veces que aparece I, i, í");

        lbl_repetiri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repetiri.setForeground(new java.awt.Color(0, 0, 255));

        jLabel7.setText("Veces que aparece O, o, ó");

        lbl_repetiro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repetiro.setForeground(new java.awt.Color(0, 0, 255));

        jLabel8.setText("Veces que aparece U, u, ú");

        lbl_repetiru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_repetiru.setForeground(new java.awt.Color(0, 0, 255));

        jLabel9.setText("Ultima letra del texto");

        lbl_ultimaletra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ultimaletra.setForeground(new java.awt.Color(0, 0, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("TRADUCCIÓN A CLAVE MURCIELAGO");

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel11.setText("Ingrese un texto o abra un archivo ");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        lbl_ultima.setText("Primera palabra del texto");

        lbl_primerapalabra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_primerapalabra.setForeground(new java.awt.Color(0, 0, 255));

        lbl_ultima1.setText("Última palabra del texto");

        lbl_ultimapalabra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ultimapalabra.setForeground(new java.awt.Color(0, 0, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("MANEJO DE CADENAS ");

        jLabel13.setText("Palabra central del texto");

        lbl_central.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_central.setForeground(new java.awt.Color(0, 0, 255));

        jLabel14.setText("Palabras con caracteres par");

        lbl_par.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_par.setForeground(new java.awt.Color(0, 0, 255));

        jLabel15.setText("Palabras con caracteres impar");

        lbl_impar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_impar.setForeground(new java.awt.Color(0, 0, 255));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem3.setText("Ayuda");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edición ");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        copiar.setText("Copiar");
        copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiarActionPerformed(evt);
            }
        });
        jMenu3.add(copiar);

        pegar.setText("Pegar");
        pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegarActionPerformed(evt);
            }
        });
        jMenu3.add(pegar);

        cortar.setText("Cortar");
        cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortarActionPerformed(evt);
            }
        });
        jMenu3.add(cortar);

        mayuscula.setText("Mayuscula");
        mayuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayusculaActionPerformed(evt);
            }
        });
        jMenu3.add(mayuscula);

        minuscula.setText("Borrar");
        minuscula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusculaActionPerformed(evt);
            }
        });
        jMenu3.add(minuscula);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbl_ultima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_ultimaletra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_primeraletra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl_primerapalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_ultima1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_ultimapalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_par, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_repetira, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_aceptar))
                                            .addComponent(lbl_repetire, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_repetiri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_repetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_repetiru, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_central, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_impar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(16, 16, 16))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(jLabel12)
                    .addContainerGap(215, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_aceptar)
                    .addComponent(lbl_repetira, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lbl_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_repetire, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(lbl_primeraletra, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(lbl_repetiri, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lbl_repetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_ultimaletra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_repetiru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ultima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_primerapalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ultima1)
                    .addComponent(lbl_central, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ultimapalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_par, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(lbl_impar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel12)
                    .addContainerGap(487, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        jOptionPane1.showMessageDialog (null, "Creado por: Gabriel Escobar \n Cualquier pregunta comunicarse a: gescobarc3@miumg.edu.gt");
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    
    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        int seleccion =jFileChooser1.showOpenDialog(jMenu1);
        if (seleccion==0){
            try {
                BufferedReader reader = null;
                File archivo = jFileChooser1.getSelectedFile();
                reader = new BufferedReader(new FileReader(archivo));
                String linea =reader.readLine();
                while (linea != null){
                    jTextArea1.append(linea);
                    jTextArea1.append(System.getProperty("line.separator"));
                    linea = reader.readLine();
                    
                }
                reader.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
int seleccion = jFileChooser1.showSaveDialog(jTextArea1);
if (seleccion == 0){
    try {
        PrintWriter writer = null;
        File archivo = jFileChooser1.getSelectedFile();
        writer = new PrintWriter (archivo);
        writer.print(jTextArea1.getText());
        writer.close();
    } catch (FileNotFoundException ex) {
        Logger.getLogger(frm_principal.class.getName()).log(Level.SEVERE, null, ex);
    }
    
}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void lbl_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_aceptarActionPerformed
int numtexto = jTextArea1.getText().length()+1;
lbl_cantidad.setText(String.valueOf(numtexto)); 

String palabras = jTextArea1.getText();
StringTokenizer st = new StringTokenizer (palabras);
lbl_palabras.setText(""+st.countTokens());

String primeraletra = jTextArea1.getText();
lbl_primeraletra.setText(""+ primeraletra.charAt(0));

String repetira = jTextArea1.getText().toUpperCase().trim();
int contador = 0;

for (int x= 0; x < repetira.length(); x++){
    
    if (repetira.charAt (x)== 'A' || repetira.charAt(x)== 'a'||repetira.charAt(x)== 'á'){
        
        contador++;
    }
}

lbl_repetira.setText(""+contador);

String repetire = jTextArea1.getText().toUpperCase().trim();
int contador1 = 0;

for (int x= 0; x < repetire.length(); x++){
    
    if (repetire.charAt (x)== 'E' || repetire.charAt(x)== 'e'|| repetire.charAt(x)== 'é'){
        
        contador1++;
    }
}

lbl_repetire.setText(""+contador1);

String repetiri = jTextArea1.getText().toUpperCase().trim();
int contador2 = 0;

for (int x= 0; x < repetiri.length(); x++){
    
    if (repetiri.charAt (x)== 'I' || repetiri.charAt(x)== 'i'|| repetiri.charAt(x)== 'í'){
        
        contador2++;
    }
}

lbl_repetiri.setText(""+contador2);

String repetiro = jTextArea1.getText().toUpperCase().trim();
int contador3 = 0;

for (int x= 0; x < repetiro.length(); x++){
    
    if (repetiro.charAt (x)== 'O' || repetiro.charAt(x)== 'o'|| repetiro.charAt(x)== 'ó'){
        
        contador3++;
    }
}

lbl_repetiro.setText(""+contador3);

String repetiru = jTextArea1.getText().toUpperCase().trim();
int contador4 = 0;

for (int x= 0; x < repetiru.length(); x++){
    
    if (repetiru.charAt (x)== 'U' || repetiro.charAt(x)== 'u'|| repetiru.charAt(x)== 'ú'){
        
        contador4++;
    }
}

lbl_repetiru.setText(""+contador4);


String palabra = jTextArea1.getText();
StringTokenizer tokens = new StringTokenizer (palabra);
String primerapalabra = tokens.nextToken();
lbl_primerapalabra.setText (primerapalabra);


String uletra = jTextArea1.getText();
String lastCharacter = uletra.substring(uletra.length() - 1);
char[] lastChar = lastCharacter.toCharArray();
lbl_ultimaletra.setText (""+lastChar[lastChar.length - 1]);

String upalabra = jTextArea1.getText();
String[] parts = upalabra.split(" ");
String lastWord = parts[parts.length - 1];
lbl_ultimapalabra.setText(lastWord);


String letras = "abcdefghijklmnñopqrstuvwxyz";
String mensaje = jTextArea1.getText();

String codigo[] = new String[30];
String traducir = "";
codigo[0] = "7"; 
codigo[1] = "b";
codigo[2] = "3";
codigo[3] = "d";
codigo[4] = "5";
codigo[5] = "f";
codigo[6] = "8";
codigo[7] = "h";
codigo[8] = "4";
codigo[9] = "j";
codigo[10] = "k";
codigo[11] = "6";
codigo[12] = "0";
codigo[13] = "n";
codigo[14] = "ñ";
codigo[15] = "9";
codigo[16] = "p";
codigo[17] = "q";
codigo[18] = "2";
codigo[19] = "s";
codigo[20] = "t";
codigo[21] = "1";
codigo[22] = "v";
codigo[23] = "w";
codigo[24] = "x";
codigo[25] = "y";
codigo[26] = "z";

for  (int i = 0; i < mensaje.length() ; i++){ 
if (mensaje.charAt(i)==' ') traducir = traducir+' ';
else {
for  (int j = 0; j < letras.length() ; j++) {
if (mensaje.charAt(i) == letras.charAt(j))
traducir = traducir + codigo[j];
}
}
}
jTextArea2.setText(traducir);


String palabrac = jTextArea1.getText();
String pal = palabrac.substring(palabrac.length()-1);
String[] palabracarray = jTextArea1.getText().split(" ");
String [] chararray = palabrac.split("");
int tam = 0;

for (int i = 0; i< palabracarray.length; i++){
    
    tam ++;
}
int centro = tam/2;
lbl_central.setText (palabracarray[centro]);


String [] valorarray = palabra.split(" ");
int sumapar =0;
int sumaimpar =0;

for (int i = 0; i < valorarray.length; i++){
    String ambos = valorarray[i];
    int conteo = ambos.length();
    
    if (conteo % 2 == 0){
        
        sumapar = sumapar + 1;
    } else {
        
        sumaimpar = sumaimpar + 1;

    }
    
}
lbl_par.setText (Integer.toString(sumapar));
lbl_impar.setText(Integer.toString(sumaimpar));
// TODO add your handling code here:
    }//GEN-LAST:event_lbl_aceptarActionPerformed

    private void copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiarActionPerformed
jTextArea1.copy();
        // TODO add your handling code here:
    }//GEN-LAST:event_copiarActionPerformed

    private void pegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegarActionPerformed
jTextArea1.paste();        // TODO add your handling code here:
    }//GEN-LAST:event_pegarActionPerformed

    private void mayusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayusculaActionPerformed
      String mensaje = jTextArea1.getText().toUpperCase().trim(); 
      jTextArea1.setText(""+ mensaje.replace('r','l'));
    }//GEN-LAST:event_mayusculaActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void minusculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusculaActionPerformed
     String mensaje = jTextArea1.getText().toUpperCase().trim(); 
      jTextArea1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_minusculaActionPerformed

    private void cortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortarActionPerformed
jTextArea1.cut();        // TODO add your handling code here:
        
    }//GEN-LAST:event_cortarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem copiar;
    private javax.swing.JMenuItem cortar;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton lbl_aceptar;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_central;
    private javax.swing.JLabel lbl_impar;
    private javax.swing.JLabel lbl_palabras;
    private javax.swing.JLabel lbl_par;
    private javax.swing.JLabel lbl_primeraletra;
    private javax.swing.JLabel lbl_primerapalabra;
    private javax.swing.JLabel lbl_repetira;
    private javax.swing.JLabel lbl_repetire;
    private javax.swing.JLabel lbl_repetiri;
    private javax.swing.JLabel lbl_repetiro;
    private javax.swing.JLabel lbl_repetiru;
    private javax.swing.JLabel lbl_ultima;
    private javax.swing.JLabel lbl_ultima1;
    private javax.swing.JLabel lbl_ultimaletra;
    private javax.swing.JLabel lbl_ultimapalabra;
    private javax.swing.JMenuItem mayuscula;
    private javax.swing.JMenuItem minuscula;
    private javax.swing.JMenuItem pegar;
    // End of variables declaration//GEN-END:variables
}
